### ISSUE TITLE
Circall_wt and Circall_bsj in Circall_recount.sh missing

### ISSUE THREAD

**Issue by solomoncharles77** [datngu/cscQTL#1]
Hi it appears two scripts Circall_wt and Circall_bsj call within Circall_recount.sh are missing.

**Comment by datngu** [comment]
Hello, if you are running the pipeline with the attached containers, these tool should be available.

**Comment by solomoncharles77** [comment]
Thanks a lot for the quick response.
Yes, I am running the container but I've got hundreds of samples and  it is taking forever on our HPC. I want to manually complete the pipeline for a few samples while I wait for the container to finish. I would be glad if you let me know how to get hold of those tools.

**Comment by datngu** [comment]
Thank you for your interest in our approach! If you have constraints in computational resources, I recommend running circular RNA detection tools separately for each tool and RNA-seq run, then aggregating the results to for consensus filtering and requantification with our proposed approach. You can also detect circQTL with any circular RNA detection input, as long as you have can manually convert the quantified input into the format used here: https://github.com/datngu/cscQTL/blob/main/data/bed/EGAR00001193012.bed. QTL detection step can run independently using https://github.com/datngu/cscQTL/blob/main/cscQTL_bed.nf. Regarding your reported issues, If you're interested in running Circall with a standard CLI interface, we’ve provided a Docker tutorial at https://github.com/datngu/Circall. The same container should work with Singularity, which may be easier to run in HPC environments.

Best wishes!
Dat

**Comment by solomoncharles77** [comment]
Thanks a lot for making the pipeline available. Thanks for the pointers.
